[project]
name = "notebooks"
version = "2.18.0"
requires-python = "~=3.11.0"

[tool.uv]
package = false
conflicts = [
    [
      { group = "elyra-preferred" },
      { group = "elyra-trustyai" }
    ],
    [
      { group = "elyra-preferred" },
      { group = "trustyai" }
    ],
    [
      { group = "datascience-preferred" },
      { group = "datascience-trustyai" },
    ],
    [
      { group = "datascience-preferred" },
      { group = "trustyai" }
    ]
]

[tool.uv.sources]

[[tool.uv.index]]
url = "https://pypi.org/simple"
name = "pypi"
verify_ssl = true

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu126"
name = "pytorch"
verify_ssl = true

[dependency-groups]

############################
# Python Dependency Groups #
############################

base = [
    "wheel ~=0.45.1",
    "setuptools ~=75.8.2"
]

jupyter-base = [
    "jupyterlab ==4.2.7",
    "jupyter-server ~=2.15.0",
    "jupyter-server-proxy ~=4.4.0",
    "jupyter-server-terminals ~=0.5.3",
    "jupyterlab-git ~=0.50.1",
    "nbdime ~=4.0.2",
    "nbgitpuller ~=1.2.2"
]

elyra-base = [
    "odh-elyra ==4.2.0",
    "jupyterlab-lsp ~=5.1.0",
    "jupyterlab-widgets ~=3.0.13",
    "jupyter-resource-usage ~=1.1.1"
]

elyra-preferred = [
    "jupyter-bokeh ~=4.0.5"
]

elyra-trustyai = [
    "jupyter-bokeh ~=3.0.5"
]

db-connectors = [
    "pymongo ~=4.11.2",
    "psycopg ~=3.2.5",
    "pyodbc ~=5.2.0",
    "mysql-connector-python ~=9.2.0"
]

# onnxconverter-common ~=1.13.0 required for skl2onnx, as upgraded version is not compatible with protobuf
datascience-base = [
    "boto3 ~=1.37.8",
    "kafka-python-ng ~=2.2.3",
    "kfp ~=2.12.1",
    "plotly ~=6.0.0",
    "scipy ~=1.15.2",
    "skl2onnx ~=1.18.0",
    "onnxconverter-common ~=1.13.0",
    "codeflare-sdk ~=0.27.0",
    "kubeflow-training ==1.9.0"
]

datascience-preferred = [
    "matplotlib ~=3.10.1",
    "numpy ~=2.2.3",
    "pandas ~=2.2.3",
    "scikit-learn ~=1.6.1"
]

datascience-trustyai = [
    "matplotlib ~=3.6.3",
    "numpy ~=1.24.1",
    "pandas ~=1.5.3",
    "scikit-learn ~=1.2.1"
]

trustyai = [
    { name = "torch", version = "==2.6.0+cu126", index = "pytorch" },
    "transformers ~=4.49.0",
    "datasets ~=3.4.1",
    "accelerate ~=1.5.2",
    "trustyai ~=0.6.1"
]

#########################
# Workench Image Groups #
#########################

jupyter-minimal-image = [
    { include-group = "base" },
    { include-group = "jupyter-base" }
]

jupyter-datascience-image = [
    { include-group = "base" },
    { include-group = "jupyter-base" },
    { include-group = "elyra-base" },
    { include-group = "elyra-preferred" },
    { include-group = "datascience-base" },
    { include-group = "datascience-preferred" },
    { include-group = "db-connectors" }
]

jupyter-trustyai-image = [
    { include-group = "base" },
    { include-group = "jupyter-base" },
    { include-group = "elyra-base" },
    { include-group = "elyra-trustyai" },
    { include-group = "datascience-base" },
    { include-group = "datascience-trustyai" },
    { include-group = "db-connectors" },
    { include-group = "trustyai" }
]
